### ISSUE TITLE
como probar el proyecto ?

### ISSUE THREAD

**Issue by jmery24** [akmsw/armame-el-doparti-desktop#2]
Hola como estas ?
me gustaria ver el proyecto. 
me podrias indicar como hacer si es posible ?

Gracias
slds

**Comment by xinaras** [comment]
Hola, jmery24.

La versión que se puede probar de la rama `main` _(correspondiente a la versión 2.1 del programa)_ está completamente descontinuada y obsoleta por tratarse de código muy pobre escrito hace ya muchos años. No se le hará mantenimiento de ningún tipo y los bugs que posea no serán corregidos. La versión en desarrollo ofrece muchísimas mejoras de performance, de estabilidad y de compatibilidad de la mano de nuevas funcionalidades. **No recomiendo probar la versión 2.1**.
Por otro lado, la versión de la rama `develop` aún no ha sido finalizada. Estoy trabajando en ello tanto como puedo teniendo en cuenta que no dispongo del tiempo que quisiera dedicarle.

Desafortunadamente, en este momento no puedo ofrecerte un archivo ejecutable o un instalador de ninguna de las dos versiones, ya que la versión 2.1 no está bajo mantenimiento hace mucho tiempo, y la versión 3.0 aún no está terminada como para publicar un release, y _—hasta no estar finalizada—_ no está en mis planes armar un ejecutable "parcial". Sin embargo, se puede probar el software si disponés de algún IDE o editor de texto, las herramientas de desarrollo necesarias para compilar y correr aplicaciones en Java, y Git instalado en tu equipo. Es mucho para explicar por acá, podés encontrar bastantes tutoriales de ello en internet. Si tenés lo que se necesita, podés clonar el repositorio sobre la rama que quieras probar, compilar el programa y ejecutarlo. **Recordá que el proyecto está protegido al día de la fecha bajo licencia GPL-3.0**.

En caso de que no puedas probarlo de tal manera, lamentablemente no puedo ofrecerte otra alternativa más que esperar a que publique un release con el ejecutable del programa completamente finalizado. Por el momento no puedo dar una fecha estimada de finalización. Disculpá las molestias.

¡Saludos!
